name: Test NPM audit Action
on: [pull_request]

jobs:
  validate-npm-audit:
    runs-on: ubuntu-latest
    name: Returns NPM audit is valid
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get result
        id: get_result
        uses: ./
        with:
          path_to_npm_project: test_dir/nest
      - name: Print the result
        run: echo "${{ steps.get_result.outputs.valid }}"